//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalTracker.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Appraisal
    {

        //appraisal ID
        public int ID { get; set; }

        //employee ID
        public int EmployeeID { get; set; }

        //Employee name
        [Display(Name = "Employee Name")]
        public string EmpName { get; set; }

        //Appraisal description
        [Required]
        public string Description { get; set; }

        //Employee previous CTC
        [Display(Name ="Previous Salary")]
        public int OLDSalary { get; set; }

        //Employee current CTC
        [Display(Name = "Current Salary")]
        public int NewSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
