//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Appraisals = new HashSet<Appraisal>();
        }

        //employee ID
        public int ID { get; set; }

        //employee name
        [Required]
        [RegularExpression("^([a-zA-Z '-]+)$",ErrorMessage ="Employee name must contain alphabets")]
        [Display(Name = "Employee Name")]
        public string EmpName { get; set; }

        //employee contact
        [Required]
        public string Contact { get; set; }

        //Joining date
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Joining Date")]
        public System.DateTime JoinDate { get; set; }

        //employee ctc
        [Required]
        public int Salary { get; set; }

        //employee totalexperience
        [Required]
        [Range(1, 50, ErrorMessage = "Only positive number allowed")]
        public int TotalExperience { get; set; }

        //employee appraisal date
        [Display(Name = "Last Appraisal Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime AppraisalDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appraisal> Appraisals { get; set; }
    }
}
